# -*- coding: utf-8 -*-
"""Assignment_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9whwzzdFYeBz8AcNPTIWe1owhxX643t
"""

# Task 1: Create a Dictionary of Student Marks

student_marks = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "David": 90
}


student_name = input("Enter the student's name: ")


if student_name in student_marks:
    print(f"{student_name}'s marks: {student_marks[student_name]}")
else:
    print(f"Student '{student_name}' not found in the record.")

# Task 2: Demonstrate List Slicing

numbers = list(range(1, 11))


first_five = numbers[:5]


reversed_list = first_five[::-1]

print("Original list:", numbers)
print("Extracted list:", first_five)
print("Reversed list:", reversed_list)

